#!/bin/bash

#SBATCH --job-name=romeo
#SBATCH --ntasks-per-node=4
#SBATCH --mem=16G
#SBATCH --time=01:00:00

# Author: Ashley Stewart

export container=romeo_3.2.8_20220224

echo "[DEBUG] ls ../"
ls ../

echo "[DEBUG] ls ../*"
ls ../*

echo "[DEBUG] ls ../*/output"
ls ../*/output

echo "[INFO] Installing Julia v1.9.3..."
if [ ! -d "julia-1.9.3" ]; then
    wget https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.3-linux-x86_64.tar.gz
    tar zxvf julia-1.9.3-linux-x86_64.tar.gz
    rm -rf julia-1.9.3-linux-x86_64.tar.gz
fi
export PATH="\${PATH}:`pwd`/julia-1.9.3/bin"
export JULIA_DEPOT_PATH=`pwd`/julia_depot

echo "[INFO] Running Julia script..."
./main.jl

